services:
  app:
    build: ./app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/users
    volumes:
      - ./app:/usr/src/app
    command: ["node", "index.js"]

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
